version: '2'
services:
  photonbbs:
    build: ..
    image: fewtarius/photonbbs
    hostname: photonbbs
    network_mode: bridge
    devices:
    - /dev:/dev:rwm
    - /lib/modules:/lib/modules:rwm
    ports:
    - 23:23/tcp
    privileged: true
    tty: true
    environment:
    - PHOTONMUD_DEBUG=0
    - PHOTON_MONSTER_DEBUG=0
    - PHOTON_ROOMS_DEBUG=0
    volumes:
    - appdata:/appdata:rw

volumes:
  appdata:
